language: node_js
node_js:
  - 0.10

env:
  - TRAVIS=true LEGACY_RENDER=true

# Found this gem in travis's code
# use depth=1 to make cloning faster
git:
  depth: 1
  submodules: false

install:
  - make install

script:
  - make test